### ISSUE TITLE
Standardize application parameters and argocd variables

### ISSUE THREAD

**Issue by Karandash8** [Karandash8/make-argocd-fly#91]
There is already a block of mandatory argocd variables. `project` and `destination_namespace` application parameters shall go to argocd variables too. Final block shall look like:
```
argocd:
  namespace: <argocd_namespace>  ## namespace for ArgoCD `Application` resource
  finalizers: <argocd_finalizers>  ## (OPTIONAL) default: []
  project: <project_name>  ## ArgoCD project name
  source:
    repo_url: <argocd_repo_url>  ## URL to the Git repository
    target_revision: <argocd_target_revision>  ## target revision for the Git repository
  destination:
    server: <kube_apiserver>  ## kube-apiserver address
    namespace: <namespace>  ## default namespace where the application resources will be deployed
  sync_policy: <argocd_sync_policy>  ## (OPTIONAL) default: {}
  ignoreDifferences: <argocd_ignoreDifferences>  ## (OPTIONAL) default: []
```
